Manifold SDK integration
reservoirprotocol/core pull request #54
Opened 2022-11-21 14:28 UTC by vikinatora

2022-11-22 09:35 UTC, georgeroman requested changes

2022-11-22 09:35 UTC, georgeroman commented on packages/sdk/src/manifold/types.ts
> +export type BNHex = {
This is just an `ethers.js` `BigNumber` represented as an object, should replace it with a regular `string`.

2022-11-22 09:35 UTC, georgeroman commented on packages/sdk/src/manifold/types.ts
> +export type ApiListingTokenDetails = BaseTokenDetails & {
We want to be fully unaware of the existence of the API, we just want a standard order format that the API response can be converted to. We should probably remove any API-specific types/fields.

2022-11-22 09:35 UTC, georgeroman commented on packages/sdk/src/manifold/types.ts
> +  deliverBPS?: number;
Let's have all of these mandatory, and instead of `null` and `undefined` use `0` as the default (which is what the exchange contract uses).

2022-11-22 09:35 UTC, georgeroman commented on packages/sdk/src/manifold/types.ts
> +export type ApiListingTokenDetails = BaseTokenDetails & {
These seems to be the all the details of the order that are available on-chain (and that we want to save):
```
    event CreateListing(uint40 indexed listingId, uint16 marketplaceBPS, uint16 referrerBPS, uint8 listingType, uint24 totalAvailable, uint24 totalPerSale, uint48 startTime, uint48 endTime, uint256 initialAmount, uint16 extensionInterval, uint16 minIncrementBPS, address erc20, address identityVerifier);
    event CreateListingTokenDetails(uint40 indexed listingId, uint256 id, address address_, uint8 spec, bool lazy);
    event CreateListingFees(uint40 indexed listingId, uint16 deliverBPS, uint240 deliverFixed);
```

2022-11-22 09:54 UTC, georgeroman commented
Also, let's fix the conflicts.

2022-11-23 14:46 UTC, georgeroman commented
@vikinatora Looks good! Sorry pushed some changes today which resulted in some more conflicts, but once these are resolved we can merge.

2022-11-23 15:32 UTC, vikinatora commented
@georgeroman  done

2022-11-23 15:54 UTC, merged